name: test node start/stop commands

on:
  push:
    branches: [ "node-start-debug" ]
  pull_request:
    branches: [ "node-start-debug" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_cargo_clippy:
    name: Rust - Lint with Cargo Clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: Swatinem/rust-cache@v2
      - run: chmod +x test.sh && ./test.sh
