name: test node start/stop commands

on:
  push:
    branches: [ "node-start-debug" ]
  pull_request:
    branches: [ "node-start-debug" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_cargo_clippy:
    name: Rust - Lint with Cargo Clippy
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/build-trust/ockam-builder@sha256:e43dd94652096b03cc472a3c709c7335e8b166cab77b7a7b56f88fa38f3d24cc
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - uses: ./.github/actions/cargo_home_cache
      - uses: ./.github/actions/cargo_target_dir_cache
      - run: chmod +x test.sh && ./test.sh
      - uses: ./.github/actions/cargo_target_dir_pre_cache
